// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAva8XBKKY19aYdUl1zbXNOmfG2iP9iz9Q',
    appId: '1:1011652048122:web:56aae6267fd8ec94630543',
    messagingSenderId: '1011652048122',
    projectId: 'note-taking-a2ffa',
    authDomain: 'note-taking-a2ffa.firebaseapp.com',
    storageBucket: 'note-taking-a2ffa.firebasestorage.app',
    measurementId: 'G-RRD04QPQ3M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowzKkeQE-cC2DPw8q7lvhqXOapS278W0',
    appId: '1:1011652048122:ios:da66d704503a8450630543',
    messagingSenderId: '1011652048122',
    projectId: 'note-taking-a2ffa',
    storageBucket: 'note-taking-a2ffa.firebasestorage.app',
    iosBundleId: 'com.example.noteTaking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAva8XBKKY19aYdUl1zbXNOmfG2iP9iz9Q',
    appId: '1:1011652048122:web:a34a20e15f17c0be630543',
    messagingSenderId: '1011652048122',
    projectId: 'note-taking-a2ffa',
    authDomain: 'note-taking-a2ffa.firebaseapp.com',
    storageBucket: 'note-taking-a2ffa.firebasestorage.app',
    measurementId: 'G-NP8VH184ZS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowzKkeQE-cC2DPw8q7lvhqXOapS278W0',
    appId: '1:1011652048122:ios:da66d704503a8450630543',
    messagingSenderId: '1011652048122',
    projectId: 'note-taking-a2ffa',
    storageBucket: 'note-taking-a2ffa.firebasestorage.app',
    iosBundleId: 'com.example.noteTaking',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGn_vWIg6IOZCLtgBAp1hp2t507Offz8',
    appId: '1:1011652048122:android:03198063f4bb3520630543',
    messagingSenderId: '1011652048122',
    projectId: 'note-taking-a2ffa',
    storageBucket: 'note-taking-a2ffa.firebasestorage.app',
  );

}